[package]
name = "vulc_window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.29.0"
bytemuck = "1.9.1"
vulkano-win = "0.29.0"
vulkano-shaders = "0.29.0"
winit = "0.26.1"
image = "0.24.2"
fbxcel-dom = "0.0.7"
anyhow = "1.0.57"
mint = "0.5.9"
